CREATE TABLE dealer_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500)
);

CREATE TABLE dealer_locations(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    dealer_group_id BIGINT NOT NULL,
    FOREIGN KEY (dealer_group_id) REFERENCES dealer_groups(id) ON DELETE CASCADE
)